database:
  driverClass: org.postgresql.Driver
  user: HEROKU_POSTGRESQL_USERNAME
  password: HEROKU_POSTGRESQL_PASSWORD
  url: jdbc:postgresql://HEROKU_POSTGRESQL_HOSTNAME/HEROKU_POSTGRESQL_DBNAME?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
  validationQuery: "/* My Example Service Service Health Check */ SELECT 1"

http:
  port: 8080
  adminPort: 8080
  connectorType: legacy
  rootPath: /*
  ssl:
    keyStore:
    keyStorePassword:

logging:
  level: INFO
  console:
    threshold: DEBUG
    timeZone: "America/Los_Angeles"
  file:
    enabled: true
    threshold: INFO
    currentLogFilename: logs/log4j.my-example-service
    archivedLogFilenamePattern: logs/log4j.my-example-service.%d.gz
    archivedFileCount: 7
    timeZone: "America/Los_Angeles"
  syslog:
    enabled: false
    threshold: INFO
    host: localhost
    facility: user
